### ISSUE TITLE
[error] Invalid language definition in Package audio-preview

### ISSUE THREAD

**Issue by jocolamarco** [MiahNelah/audio-preview#1]
Server log:

[error] Invalid language definition in Package audio-preview: Language JSON path module/languages/en.json does not exist
[error] Invalid language definition in Package audio-preview: Language JSON path module/languages/fr.json does not exist

FVTT: 0.8.9
DND5e: 1,4,2

**Comment by MiahNelah** [comment]
Thanks for your feedback ! I release v1.0.6 to fix this issue.
