### ISSUE TITLE
New update removed access in Starfinder System

### ISSUE THREAD

**Issue by Iankid** [MiahNelah/audio-preview#3]
With the new update, the module no longer appears in my module list while running Starfinder, despite being installed.

**Comment by MiahNelah** [comment]
Hi ! I did messed up versionning when preparing v10 support. I'm working on it.

**Comment by MiahNelah** [comment]
You should be able to install module again. There still on error message "k is undeifned" when trying to update, but you can ignore it since next version will be compatible with v10 only. I'll look to remove this error message.

**Comment by MiahNelah** [comment]
Issue is now fixed with a custom version : v1.0.9.1_v9. Please uninstall then reinstall Audio Preview. You shouldn't get any more error message then. Feel free to re-open this issue if you still encounter problems.
