### ISSUE TITLE
Audio Preview not available to activate in v9 build 280

### ISSUE THREAD

**Issue by weepingminotaur** [MiahNelah/audio-preview#4]
After installing Audio Preview, the module is not available in the Manage Modules list to activate. Foundry doesn't seem to recognize that it exists.

**Comment by MiahNelah** [comment]
Thanks your feedback ! Can you tell which version of Foundry and Audio Preview you are using please ? Just tried on the latest version of Foundry, and everything works fine.

**Comment by weepingminotaur** [comment]
I'm using Foundry v9, build 280. Running the latest version of Audio Preview.

**Comment by MiahNelah** [comment]
Can you check you're using v1.0.9.1_v9 version ?

**Comment by weepingminotaur** [comment]
Ah, the version given to me on the Forge is 1.0.12, which doesn't seem to be compatible with v9. Will roll back to 1.0.9.1. Thank you!

**Comment by MiahNelah** [comment]
You can manually install latest v9 compatible version by using this manifest : https://github.com/MiahNelah/audio-preview/releases/download/1.0.9.1_v9/module.json.

**Comment by weepingminotaur** [comment]
No need; on the Forge it's very easy to install the previous version. Normally I don't get prompted for v10 updates for modules if the version isn't compatible with v9, but this one must have slipped through the cracks. Thanks again!

**Comment by MiahNelah** [comment]
My bad, I misread. It's strange this version has been installed on your setup, I'll double-check compatibility declaration. Thanks for your feedback :)

**Comment by weepingminotaur** [comment]
No problem, and thank you for this great little module!
