### ISSUE TITLE
Preview Ceases to Play After Ambient Sound Object is Saved

### ISSUE THREAD

**Issue by Red5MT** [MiahNelah/audio-preview#5]
Chrome v121.0.6167.86 (Official Build) (64-bit)
Foundry VTT v11.315
DnD5e - Fifth Edition System v2.3.1

Modules Active:
- Audio Preview v1.2 (latest version)
- libwrapper v1.12.13.0 (latest version)

- Audio Preview is disabled.
- Set down an Ambient Sound Object.
- Click 'Source File Path' button.
- Browse to an audio file and select it from the list.
- Click the preview button to preview the sound (tested with ogg and wav).
- Click 'Select File' before the preview ends.
- Click 'Update Ambient Sound'.
- If the sound duration is long enough, it will continue to play after saving.

Clicking outside the sound area or clicking a token will not stop the preview sound. The preview sound will end on it's own eventually. Refreshing the page fixes the issue. The expection I would have is that the sound preview would end when 'Select File' is clicked.

**Comment by MiahNelah** [comment]
fixed in v1.2.2

**Comment by Red5MT** [comment]
Works great. Thank you.
